/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as AuthenticatedAsistenciasRouteImport } from './routes/_authenticated/asistencias'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as AuthenticatedMiRutinaRouteImport } from './routes/_authenticated/mi-rutina'
import { Route as AuthenticatedMisPagosRouteImport } from './routes/_authenticated/mis-pagos'
import { Route as AuthenticatedMisRutinasRouteImport } from './routes/_authenticated/mis-rutinas'
import { Route as AuthenticatedPagosRouteImport } from './routes/_authenticated/pagos'
import { Route as AuthenticatedRutinasRouteImport } from './routes/_authenticated/rutinas'
import { Route as AuthenticatedSociosRouteImport } from './routes/_authenticated/socios'
import { Route as AuthenticatedGruposIdRouteImport } from './routes/_authenticated/grupos_.$id'
import { Route as AuthenticatedSociosIdRouteImport } from './routes/_authenticated/socios_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAsistenciasRoute =
  AuthenticatedAsistenciasRouteImport.update({
    id: '/asistencias',
    path: '/asistencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiRutinaRoute = AuthenticatedMiRutinaRouteImport.update({
  id: '/mi-rutina',
  path: '/mi-rutina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisPagosRoute = AuthenticatedMisPagosRouteImport.update({
  id: '/mis-pagos',
  path: '/mis-pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisRutinasRoute = AuthenticatedMisRutinasRouteImport.update({
  id: '/mis-rutinas',
  path: '/mis-rutinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagosRoute = AuthenticatedPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRutinasRoute = AuthenticatedRutinasRouteImport.update({
  id: '/rutinas',
  path: '/rutinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSociosRoute = AuthenticatedSociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposIdRoute = AuthenticatedGruposIdRouteImport.update({
  id: '/grupos_/$id',
  path: '/grupos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSociosIdRoute = AuthenticatedSociosIdRouteImport.update({
  id: '/socios_/$id',
  path: '/socios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recuperar': typeof RecuperarRoute
  '/asistencias': typeof AuthenticatedAsistenciasRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/mi-rutina': typeof AuthenticatedMiRutinaRoute
  '/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/mis-rutinas': typeof AuthenticatedMisRutinasRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/rutinas': typeof AuthenticatedRutinasRoute
  '/socios': typeof AuthenticatedSociosRoute
  '/grupos/$id': typeof AuthenticatedGruposIdRoute
  '/socios/$id': typeof AuthenticatedSociosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recuperar': typeof RecuperarRoute
  '/asistencias': typeof AuthenticatedAsistenciasRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/mi-rutina': typeof AuthenticatedMiRutinaRoute
  '/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/mis-rutinas': typeof AuthenticatedMisRutinasRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/rutinas': typeof AuthenticatedRutinasRoute
  '/socios': typeof AuthenticatedSociosRoute
  '/grupos/$id': typeof AuthenticatedGruposIdRoute
  '/socios/$id': typeof AuthenticatedSociosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/_authenticated/asistencias': typeof AuthenticatedAsistenciasRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/mi-rutina': typeof AuthenticatedMiRutinaRoute
  '/_authenticated/mis-pagos': typeof AuthenticatedMisPagosRoute
  '/_authenticated/mis-rutinas': typeof AuthenticatedMisRutinasRoute
  '/_authenticated/pagos': typeof AuthenticatedPagosRoute
  '/_authenticated/rutinas': typeof AuthenticatedRutinasRoute
  '/_authenticated/socios': typeof AuthenticatedSociosRoute
  '/_authenticated/grupos_/$id': typeof AuthenticatedGruposIdRoute
  '/_authenticated/socios_/$id': typeof AuthenticatedSociosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recuperar'
    | '/asistencias'
    | '/avisos'
    | '/configuracion'
    | '/dashboard'
    | '/grupos'
    | '/mi-cuenta'
    | '/mi-rutina'
    | '/mis-pagos'
    | '/mis-rutinas'
    | '/pagos'
    | '/rutinas'
    | '/socios'
    | '/grupos/$id'
    | '/socios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recuperar'
    | '/asistencias'
    | '/avisos'
    | '/configuracion'
    | '/dashboard'
    | '/grupos'
    | '/mi-cuenta'
    | '/mi-rutina'
    | '/mis-pagos'
    | '/mis-rutinas'
    | '/pagos'
    | '/rutinas'
    | '/socios'
    | '/grupos/$id'
    | '/socios/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/recuperar'
    | '/_authenticated/asistencias'
    | '/_authenticated/avisos'
    | '/_authenticated/configuracion'
    | '/_authenticated/dashboard'
    | '/_authenticated/grupos'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/mi-rutina'
    | '/_authenticated/mis-pagos'
    | '/_authenticated/mis-rutinas'
    | '/_authenticated/pagos'
    | '/_authenticated/rutinas'
    | '/_authenticated/socios'
    | '/_authenticated/grupos_/$id'
    | '/_authenticated/socios_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RecuperarRoute: typeof RecuperarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/asistencias': {
      id: '/_authenticated/asistencias'
      path: '/asistencias'
      fullPath: '/asistencias'
      preLoaderRoute: typeof AuthenticatedAsistenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-rutina': {
      id: '/_authenticated/mi-rutina'
      path: '/mi-rutina'
      fullPath: '/mi-rutina'
      preLoaderRoute: typeof AuthenticatedMiRutinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-pagos': {
      id: '/_authenticated/mis-pagos'
      path: '/mis-pagos'
      fullPath: '/mis-pagos'
      preLoaderRoute: typeof AuthenticatedMisPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-rutinas': {
      id: '/_authenticated/mis-rutinas'
      path: '/mis-rutinas'
      fullPath: '/mis-rutinas'
      preLoaderRoute: typeof AuthenticatedMisRutinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos': {
      id: '/_authenticated/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthenticatedPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rutinas': {
      id: '/_authenticated/rutinas'
      path: '/rutinas'
      fullPath: '/rutinas'
      preLoaderRoute: typeof AuthenticatedRutinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/socios': {
      id: '/_authenticated/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof AuthenticatedSociosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos_/$id': {
      id: '/_authenticated/grupos_/$id'
      path: '/grupos/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof AuthenticatedGruposIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/socios_/$id': {
      id: '/_authenticated/socios_/$id'
      path: '/socios/$id'
      fullPath: '/socios/$id'
      preLoaderRoute: typeof AuthenticatedSociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenciasRoute: typeof AuthenticatedAsistenciasRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedMiRutinaRoute: typeof AuthenticatedMiRutinaRoute
  AuthenticatedMisPagosRoute: typeof AuthenticatedMisPagosRoute
  AuthenticatedMisRutinasRoute: typeof AuthenticatedMisRutinasRoute
  AuthenticatedPagosRoute: typeof AuthenticatedPagosRoute
  AuthenticatedRutinasRoute: typeof AuthenticatedRutinasRoute
  AuthenticatedSociosRoute: typeof AuthenticatedSociosRoute
  AuthenticatedGruposIdRoute: typeof AuthenticatedGruposIdRoute
  AuthenticatedSociosIdRoute: typeof AuthenticatedSociosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenciasRoute: AuthenticatedAsistenciasRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedMiRutinaRoute: AuthenticatedMiRutinaRoute,
  AuthenticatedMisPagosRoute: AuthenticatedMisPagosRoute,
  AuthenticatedMisRutinasRoute: AuthenticatedMisRutinasRoute,
  AuthenticatedPagosRoute: AuthenticatedPagosRoute,
  AuthenticatedRutinasRoute: AuthenticatedRutinasRoute,
  AuthenticatedSociosRoute: AuthenticatedSociosRoute,
  AuthenticatedGruposIdRoute: AuthenticatedGruposIdRoute,
  AuthenticatedSociosIdRoute: AuthenticatedSociosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RecuperarRoute: RecuperarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
